---
- hosts: vagrant
  user: vagrant
  sudo: True
  gather_facts: no # Enable for Vagrant boxes to save time

  # Base path for includes and files
  # MUST BE SET TO ABSOLUTE PATH TO TOP OF PLAYBOOKS DIRECTORY
  vars:
    base: provision/Ubuntu_12.04_LTS
    env: dev

  vars_files:
    - $base/apache/vars.yml
    - $base/mysql/vars.yml
    - $base/php/vars.yml
    - $base/varnish/vars.yml
    - $base/jenkins/vars.yml
    - provision_overrides/${env}_vars.yml # Enable for variable overrides for the current environment

  tasks:
    # -= REQUIRED =-
    - include: $base/common/setup.yml

    # -= OPTIONAL =-
    # - include: $base/python/setup.yml
    # - include: $base/ansible/setup.yml
    # - include: $base/apache/setup.yml
    # - include: $base/drush/setup.yml
    - include: $base/php/setup.yml
    # - include: $base/phpcs/setup.yml
    # - include: $base/mysql/setup.yml
    # - include: $base/mongodb/setup.yml
    # - include: $base/node/setup.yml
    # - include: $base/grunt/setup.yml
    # - include: $base/redis/setup.yml
    # - include: $base/ruby-css/setup.yml
    # - include: $base/tools/setup.yml
    # - include: $base/varnish/setup.yml
    # - include: $base/jenkins/setup.yml
    - include: $base/sendmail-trap/setup.yml
    # - include: provision_overrides/setup.yml # Enable for custom tasks

  handlers:
    # -= OPTIONAL =-
    - include: $base/apache/handler.yml
    - include: $base/mysql/handler.yml
    - include: $base/drush/handler.yml
    - include: $base/mongodb/handler.yml
    - include: $base/tools/handler.yml
    - include: $base/varnish/handler.yml
    - include: $base/jenkins/handler.yml
